services:
  fitbuddy:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "8000:8000"
    environment:
      PSQL_URL: postgresql+asyncpg://postgres:qPz8am91@pg:5432/fitbuddy_db
    depends_on:
      pg:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: ./fitbuddy
        - action: rebuild
          path: ./poetry.lock

  pg:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qPz8am91
      POSTGRES_DB: fitbuddy_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"

volumes:
  pgdata: